services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=test
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  ts-api:
    build:
      context: .
      dockerfile: apps/ts-api/Dockerfile
    container_name: ts-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/rust
      - PORT=3000
    depends_on:
      - postgres

  ingester:
    build:
      context: .
      dockerfile: Dockerfile
      target: ingester
    container_name: ingester
    restart: always
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-test}
      - DATABASE_URL=tcp://clickhouse:9000?database=default&username=default&password=${CLICKHOUSE_PASSWORD:-test}
    depends_on:
      - postgres
      - clickhouse

  generator:
    build:
      context: .
      dockerfile: Dockerfile
      target: generator
    container_name: generator
    restart: always
    environment:
      - INGESTER_URL=http://ingester:50051
      - NUM_THREADS=4
    depends_on:
      - ingester

volumes:
  pg_data:
  clickhouse:
  ts-api:
  ingester:
  generator:
